# Prepare Data From CSV Recording

## Load File

Data is loaded from a CSV recording file, accepted through an input prompt. This includes all positional data related to the 6 trackers (HMD, Left Controller, Right Controller, Waist, Left Foot, Right Foot).

'Data is loaded into a Pandas dataframe. The primary tracking data is then extracted, leaving extraneous data such as booleans for button presses.

The extracted columns are then concatenated into a new dataframe, and the columns are renamed for ease of reading.

The columns are reorded in the order of head/r_controller/l_controller/waist/r_foot/l_foot.

The new trimmed file is written to a directory (/test_data or /train_data), for further manipulation and loading into the model.


In [17]:
import pandas as pd


#Read in CSV
def GetRecording(path):
    recording_path = "../recordings/"
    file_name = input("Input Recording File Name")
    try:
        dataframe = pd.read_csv(recording_path + file_name + ".csv")
        return dataframe, file_name
    except: 
        print("Error Reading File: Check Spelling and Try Again")
        return 0
    
    
#Seperate each tracker to seperate dataframe

def GetColByName(dataframe):
    HMD = dataframe.loc[:, ["HMD0_tx", "HMD0_ty", "HMD0_tz"]]
    
    controller_1 = dataframe.loc[:, ['controller3_tx', 'controller3_ty', 'controller3_tz']]

    controller_2 = dataframe.loc[:, ['controller4_tx', 'controller4_ty', 'controller4_tz']]

    tracker_1 = dataframe.loc[:, ['generic7_tx', 'generic7_ty', 'generic7_tz']]

    tracker_2 = dataframe.loc[:, ['generic8_tx', 'generic8_ty', 'generic8_tz']]

    tracker_3 = dataframe.loc[:, ['generic9_tx', 'generic9_ty', 'generic9_tz']]

    joined = pd.concat([HMD,controller_1, controller_2, tracker_1 ,tracker_2 ,tracker_3], axis=1)
    return joined

def AssignTracker(dataframe):
    display(dataframe.iloc[0:1,:])
    trackerNum = 7
    for x in range(3):
        trackerStr = str(trackerNum)
        tracker = input('assign generic' + trackerStr)
        dataframe.rename(columns={'generic' + trackerStr + '_tx': tracker + '_x', 'generic' + trackerStr + '_ty': tracker + "_y", 'generic' + trackerStr + '_tz': tracker + '_z'}, inplace=True)
        trackerNum += 1
        
    controllerNum = 3
    for x in range(2):
        controllerStr = str(controllerNum)
        controller = input('assign controller' + controllerStr)
        dataframe.rename(columns={'controller' + controllerStr + '_tx': controller + '_x', 'controller' + controllerStr + '_ty': controller + "_y", 'controller' + controllerStr + '_tz': controller + '_z'}, inplace=True)
        controllerNum += 1
    dataframe.rename(columns={'HMD0_tx': 'head_x', 'HMD0_ty': 'head_y', 'HMD0_tz': 'head_z'}, inplace=True)
    return dataframe

def GetDirectory():
    choice = input("train or test data:")
    if choice == "test":
        output_path = "../test_data/"
    else:
        output_path = "../train_data/"
    return output_path

def OrderFeatures(dataframe):
    head = dataframe.loc[:, ['head_x', 'head_y', 'head_z']]
    l_controller = dataframe.loc[:, ['l_controller_x', 'l_controller_y', 'l_controller_z']]
    r_controller = dataframe.loc[:, ['r_controller_x', 'r_controller_y', 'r_controller_z']]
    waist = dataframe.loc[:, ['waist_x', 'waist_y', 'waist_z']]
    r_foot = dataframe.loc[:, ['r_foot_x', 'r_foot_y', 'r_foot_z']]
    l_foot = dataframe.loc[:, ['l_foot_x', 'l_foot_y', 'l_foot_z']]
    reordered = pd.concat([head , r_controller, l_controller, waist, r_foot, l_foot], axis=1)
    return reordered

    
    
def WriteOutput(path, dataframe, filename):
    output_file = path + filename + "_trimmed.csv"
    dataframe.to_csv(output_file, index = False)
    print(file_name + " output to " + path)
    
    

# Run data trimming functions

In [41]:
recording_path = " ../recordings"

dataframe, file_name = GetRecording(recording_path)
joined = GetColByName(dataframe)
renamed = AssignTracker(joined)
path = GetDirectory()
reordered = OrderFeatures(renamed)
WriteOutput(path, reordered, file_name)


Input Recording File Name leg_raise_5


HMD0_tx     HMD0_ty   HMD0_tz  controller3_tx  controller3_ty  \
0  1.964998  158.131058  3.838474      -18.907917       92.860924   

   controller3_tz  controller4_tx  controller4_ty  controller4_tz  \
0       -9.813828       29.159588       80.373276        2.166218   

   generic7_tx  generic7_ty  generic7_tz  generic8_tx  generic8_ty  \
0     3.899813     97.88607     6.474656    21.754217    11.036432   

   generic8_tz  generic9_tx  generic9_ty  generic9_tz  
0    13.468838   -12.954676    11.488569    19.045788

assign generic7 waist
assign generic8 r_foot
assign generic9 l_foot
assign controller3 l_controller
assign controller4 r_controller
train or test data: test


leg_raise_5 output to ../test_data/


# Data Normalization

## Data Scaling

The new CSV is loaded into memory, chosen through an input prompt
The data is then split between the features (the HMD and controller tracking data), and the labels (the waist and foot trackers).
These are loaded into Numpy arrays to peform normaliztion. The output from OpenVR Recorder is upscaled by 100. To correct this the array is divided by 100

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
#from sklearn.metrics import mean_absolute_error 
from matplotlib import pyplot as plt
#import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


output_path = "../trim_output/"


#read in formatted CSV
def ReadCSV(path):
    file_name = input("Input File Name")
    try:
        dataframe = pd.read_csv(path + file_name + ".csv")
        print("Dataframe created")
    except:
        print("Error Reading File")
    return dataframe

def SplitFeaturesLabels(dataframe):
    x = dataframe.iloc[:, 0:9]
    y = dataframe.iloc[:, 9:18]
    return x, y

#Load data into Numpy array
def LoadArray(x, y):
    x_array = np.array(x)
    y_array = np.array(y)
    return x_array, y_array


def NormalizeValues (x, y):
    x =  np.divide(x, 100)
    y =  np.divide(y, 100)
    return x, y

def SampleSize(x, y):
    x_samples = x[0:600,:]
    y_samples = y[0:600,:]
    return x_samples, y_samples

def RoundValues(x, y): 
    x_rounded = np.around(x, 3)
    y_rounded = np.around(y, 3)
    return x_rounded, y_rounded



    
    

    





# Create Training Data

In [45]:
train_path = "../train_data/"
#load train data from csv
train_dataframe = ReadCSV(train_path)

#split features and labels into seperate dataframes
x_train_df, y_train_df = SplitFeaturesLabels(train_dataframe)

#convert features and labels to numpy array
x_train, y_train = LoadArray(x_train_df, y_train_df)

#Divide values in array by 100
x_samples, y_samples = NormalizeValues(x_train, y_train)

print(x_samples.shape, x_samples)
print(y_samples.shape, y_samples)

#x_train, x_test, y_train, y_test = train_test_split(x_train_normalized, y_train_normalized)





Input File Name walking_7_trimmed


Dataframe created
(600, 9) [[0.56456936 1.65256363 0.82371849 ... 0.35004543 0.81725983 0.93927994]
 [0.56244183 1.6511261  0.82760582 ... 0.35082798 0.81521797 0.94517693]
 [0.56021255 1.64923187 0.8309227  ... 0.3510099  0.81342445 0.95069672]
 ...
 [0.42225151 1.55701126 0.6327589  ... 0.21533564 0.75101753 0.71076973]
 [0.41390022 1.55681183 0.62624306 ... 0.20336998 0.75672852 0.69413803]
 [0.40570499 1.55652176 0.6195657  ... 0.19236187 0.76251534 0.67823952]]
(600, 9) [[0.56388847 0.9584938  0.82307373 ... 0.6701664  0.12568272 1.02205978]
 [0.5649939  0.95908966 0.8268927  ... 0.67017311 0.12555384 1.02190422]
 [0.5658884  0.95991432 0.83057884 ... 0.67164154 0.12405634 1.02306038]
 ...
 [0.4459425  0.94995354 0.64034004 ... 0.39146503 0.11636929 0.66756081]
 [0.43529736 0.9514679  0.63556534 ... 0.39199577 0.115468   0.66869583]
 [0.42703381 0.95304367 0.63249866 ... 0.39176373 0.11532265 0.66892319]]


# Scale Values

In [ ]:
from sklearn.preprocessing import MinMaxScaler

print(x_samples.max())
print(x_samples.min())

print(y_samples.max())
print(y_samples.min())

scaler =MinMaxScaler()
print(x_samples[0:1])
scaled = scaler.fit(x_samples)
print(scaler.transform(x_samples[0:1]))
print(scaler.inverse_transform(x_samples[0:1]))


# Reshape Training Data

In [5]:

def ReshapeData(x, y):
    x_reshaped = np.expand_dims(x, axis=1)
    y_reshaped = np.expand_dims(y, axis=1)

    return x_reshaped, y_reshaped


In [46]:
x_train, y_train = ReshapeData(x_samples, y_samples)

print(x_train.shape, y_train.shape)

print(x_train.shape[1])

print(x_train.shape[2])


(600, 1, 9) (600, 1, 9)
1
9


# Create Test / Validation Data

In [42]:
#Create a single test data file

test_path = "../test_data/"


test_dataframe = ReadCSV(test_path)

#split features and labels into seperate dataframes
x_test_df, y_test_df = SplitFeaturesLabels(test_dataframe)

#convert features and labels to numpy array
x_test, y_test = LoadArray(x_test_df, y_test_df)

#Divide values in array by 100
x_test_normalized, y_test_normalized = NormalizeValues(x_test, y_test)

x_test_samples, y_test_samples = SampleSize(x_test_normalized, y_test_normalized)

x_test, y_test = ReshapeData(x_test_samples, y_test_samples)

print(x_test.shape, y_test.shape)

print(x_test.shape[1])

KeyboardInterrupt: Interrupted by user

# Combine Test and Train datasets

Combine all data sets in /train_data and /test_data into one, for more samples when training 

In [7]:
#import modules 

import os
import pandas as pd
import numpy as np


In [8]:

#Combine all datasets in a directory into one dataframe
def CombineDatasets(path):
    data_list = []
    for file in os.listdir(path):
        filename = os.fsdecode(file)
        if filename.endswith(".csv"):
            df = pd.read_csv(path + filename)
            
            data_list.append(df)
         

    data_df = pd.concat(data_list, axis=0, ignore_index=True)
    return data_df



In [9]:

#combine data in a directory into two lists of x and y features
def DatasetsLists(path):
    x_list = []
    y_list = []
    for file in os.listdir(path):
        filename = os.fsdecode(file)
        print(filename)
        if filename.endswith(".csv"):
            df = pd.read_csv(path + filename)
            x_features, y_features = SplitFeaturesLabels(df)
            x_train, y_train = LoadArray(x_features, y_features)
            x_normalized, y_normalized = NormalizeValues(x_train, y_train)
            x_reshape, y_reshape = ReshapeData(x_normalized, y_normalized)
            x_list.append(x_reshape)
            y_list.append(y_reshape)
    return x_list, y_list



In [56]:
train_path = "../train_data/"
x, y = DatasetsLists(train_path)


.ipynb_checkpoints
arm_raise_1_trimmed.csv
arm_raise_3_trimmed.csv
boxing_1_trimmed.csv
crouch_walking_1_trimmed.csv
jumping_1_trimmed.csv
jumping_2_trimmed.csv
jumping_3_trimmed.csv
leg_raise_1_trimmed.csv
leg_raise_2_trimmed.csv
leg_raise_3_trimmed.csv
leg_raise_4_trimmed.csv
picking_up_1_trimmed.csv
running_on_spot_2_trimmed.csv
sitting_on_floor_1_trimmed.csv
sitting_standing_1_trimmed.csv
sitting_standing_2_trimmed.csv
sitting_standing_3_trimmed.csv
walking_1_train.csv
walking_2_test.csv
walking_3_trimmed.csv
walking_5_trimmed.csv
walking_6_trimmed.csv
walking_7_trimmed.csv


Combine all data in the training data directory 

In [43]:
train_path = "../train_data/"

combined_train_dataframe = CombineDatasets(train_path)

x_train, y_train = SplitFeaturesLabels(combined_train_dataframe)
        
x_train_arr, y_train_arr = LoadArray(x_train, y_train)

#Divide values in array by 100
x_train_normalized, y_train_normalized = NormalizeValues(x_train_arr, y_train_arr)

x_train, y_train = ReshapeData(x_train_normalized, y_train_normalized)

print(x_train.shape, y_train.shape)


(16108, 1, 9) (16108, 1, 9)


Combine all data in the test data directory

In [44]:
test_path = "../test_data/"

combined_test_dataframe = CombineDatasets(test_path)

x_test, y_test = SplitFeaturesLabels(combined_test_dataframe)
        
x_test_arr, y_test_arr = LoadArray(x_test, y_test)

x_test_normalized, y_test_normalized = NormalizeValues(x_test_arr, y_test_arr)

x_test, y_test = ReshapeData(x_test_normalized, y_test_normalized)

print(x_test.shape)
print(x_test[0:1,:,:])
print(x_test_normalized.shape)


(5400, 1, 9)
[[[ 0.07488835  1.60079437 -0.06116605  0.29804235  0.82701195
   -0.13233584 -0.16509771  0.80914047 -0.10186529]]]
(5400, 9)


# Model Creation and Training

In [79]:
#import required modules

from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, BatchNormalization
import tensorflow as tf
from keras.layers import LSTM, GRU
from tensorflow.keras.optimizers import SGD
from keras.layers.core import Dense, Activation, Dropout
from keras.losses import SparseCategoricalCrossentropy

tf.keras.backend.set_floatx('float64')


# Model Functions

In [164]:
#Fit model to two equally sized lists of x features and y labels 

def FitToList(x, y, model, epoch, b_size, verbose):
    for i in range(len(x)):
        print(i)
        print(x[i].shape)
        print(y[i].shape)
        model.fit(x[i], y[i], epochs=epoch,batch_size=b_size, verbose=verbose)
        
 # fit the model to a given set of features (x) and labels (y)    
def FitModel(x, y, model, epoch, b_size):
    model.fit(x, y, validation_split=0.33, epochs=epoch,batch_size = b_size)

    
def EvaluateModel(x, y, model):
    metrics = model.evaluate(x, y, batch_size=256)
    
    
    
def PredictModel(x, y, model):
    predictions = model.predict(x)
    y_reshaped = y.reshape(-1,9)
    return predictions, y_reshaped


def DisplayPredictions(prediction, actual, range_1, range_2):
    if range_2 <= 0:
        r_1 = 0
        r_2 = len(prediction)
    else:
        r_1 = range_1
        r_2 = range_2
    print("predictions shape:", prediction.shape)
    prediction_df = pd.DataFrame(prediction, columns=["Waist_X", "Waist_Y", "Waist_Z", "R_Foot_X", "R_Foot_Y", "R_Foot_Z", "L_Foot_X", "L_Foot_Y", "L_Foot_Z"])
    actual_df = pd.DataFrame(actual, columns=["Waist_X", "Waist_Y", "Waist_Z", "R_Foot_X", "R_Foot_Y", "R_Foot_Z", "L_Foot_X", "L_Foot_Y", "L_Foot_Z"])
    print("Actual Values")
    display(actual_df[r_1:r_2])
    print("Predicited Values")
    display(prediction_df[r_1:r_2])
    return actual_df, prediction_df
    

        

# Model 1

In [8]:
sgd = SGD(learning_rate=0.001, momentum=0.8, decay=0.999, nesterov=False)

tf.keras.backend.set_floatx('float64')

model = Sequential()
model.add(GRU(16, return_sequences=True, input_shape=(5, 9)))
model.add(Dropout(0.2))
model.add(GRU(16, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(9, activation = "linear"))

model.compile(loss='mse', optimizer="adam")

print ('model compiled')

print (model.summary())

model compiled
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru (GRU)                   (None, 1, 16)             1296      
                                                                 
 dropout (Dropout)           (None, 1, 16)             0         
                                                                 
 gru_1 (GRU)                 (None, 16)                1632      
                                                                 
 dropout_1 (Dropout)         (None, 16)                0         
                                                                 
 dense (Dense)               (None, 9)                 153       
                                                                 
Total params: 3,081
Trainable params: 3,081
Non-trainable params: 0
_________________________________________________________________
None


# Model 2 

In [115]:
model_2 = Sequential()

#add one GRU layer of 64 cellss with input shape 1,9
model_2.add(GRU(64, input_shape=(1, 9)))
#model_2.add(Dropout(0.5))

#Add Batch Normalization layer
#model_2.add(BatchNormalization())


#Add dropout layer
#model_2.add(Dropout(0.2))

#Add Dense layer with 9 outputs
model_2.add(Dense(9))

print(model_2.summary())

#Compile model
model_2.compile(
    loss="mse",
    optimizer="adam",
    metrics=["accuracy"],
)



Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_12 (GRU)                (None, 64)                14400     
                                                                 
 dense_7 (Dense)             (None, 9)                 585       
                                                                 
Total params: 14,985
Trainable params: 14,985
Non-trainable params: 0
_________________________________________________________________
None


In [112]:
#Fit single dataset to model
FitModel(x_train, y_train, model_2, 200, 1)

Epoch 1/200
401/401 [==============================] - 2s 2ms/step - loss: 0.0430 - accuracy: 0.8404 - val_loss: 0.0129 - val_accuracy: 0.8191
Epoch 2/200
401/401 [==============================] - 1s 1ms/step - loss: 0.0073 - accuracy: 0.9127 - val_loss: 0.0125 - val_accuracy: 0.5628
Epoch 3/200
401/401 [==============================] - 1s 1ms/step - loss: 0.0068 - accuracy: 0.9177 - val_loss: 0.0104 - val_accuracy: 0.6231
Epoch 4/200
401/401 [==============================] - 1s 1ms/step - loss: 0.0064 - accuracy: 0.9377 - val_loss: 0.0099 - val_accuracy: 0.6382
Epoch 5/200
401/401 [==============================] - 0s 1ms/step - loss: 0.0059 - accuracy: 0.9501 - val_loss: 0.0103 - val_accuracy: 0.5729
Epoch 6/200
401/401 [==============================] - 0s 1ms/step - loss: 0.0055 - accuracy: 0.9426 - val_loss: 0.0095 - val_accuracy: 0.6583
Epoch 7/200
401/401 [==============================] - 0s 1ms/step - loss: 0.0054 - accuracy: 0.9476 - val_loss: 0.0095 - val_accuracy: 0.7035

In [116]:
#Fit list of datasets to model

FitToList(x, y, model_2, 20, 1, 1)

0
(905, 1, 9)
(905, 1, 9)
Epoch 1/20
905/905 [==============================] - 3s 2ms/step - loss: 0.0021 - accuracy: 0.9945
Epoch 2/20
905/905 [==============================] - 1s 1ms/step - loss: 2.1529e-05 - accuracy: 1.0000
Epoch 3/20
905/905 [==============================] - 1s 997us/step - loss: 1.9848e-05 - accuracy: 1.0000
Epoch 4/20
905/905 [==============================] - 1s 940us/step - loss: 2.0158e-05 - accuracy: 1.0000
Epoch 5/20
905/905 [==============================] - 1s 853us/step - loss: 2.0968e-05 - accuracy: 1.0000
Epoch 6/20
905/905 [==============================] - 1s 843us/step - loss: 2.2221e-05 - accuracy: 1.0000
Epoch 7/20
905/905 [==============================] - 1s 854us/step - loss: 2.1092e-05 - accuracy: 1.0000
Epoch 8/20
905/905 [==============================] - 1s 848us/step - loss: 2.0868e-05 - accuracy: 1.0000
Epoch 9/20
905/905 [==============================] - 1s 853us/step - loss: 1.9991e-05 - accuracy: 1.0000
Epoch 10/20
905/905 [=======

In [117]:
EvaluateModel(x_test, y_test, model_2)

22/22 [==============================] - 0s 3ms/step - loss: 0.1530 - accuracy: 0.7135
Loss:  0.1529950911137793


In [178]:
pred, actual = PredictModel(x_test, y_test, model_2)
print(actual.shape)
print(pred.shape)
toWriteActual, toWritePred = DisplayPredictions(pred, actual, 4000, 4050)



(5400, 9)
(5400, 9)
predictions shape: (5400, 9)
Actual Values


Waist_X   Waist_Y   Waist_Z  R_Foot_X  R_Foot_Y  R_Foot_Z  L_Foot_X  \
4000  0.568578  0.948957  0.022448  0.443972  0.099626  0.040721  0.847469   
4001  0.559899  0.950990  0.032180  0.444332  0.099212  0.041662  0.843127   
4002  0.552315  0.952658  0.041153  0.445992  0.098248  0.041867  0.839128   
4003  0.545255  0.954177  0.050479  0.446416  0.097923  0.042506  0.833094   
4004  0.538411  0.956142  0.058618  0.445989  0.098010  0.042564  0.824971   
4005  0.532336  0.957229  0.066987  0.446254  0.098038  0.043005  0.815174   
4006  0.526953  0.958167  0.075301  0.446580  0.097753  0.043268  0.802805   
4007  0.521210  0.958752  0.083070  0.446938  0.097715  0.043523  0.788901   
4008  0.516434  0.959480  0.089992  0.447252  0.097746  0.043566  0.773595   
4009  0.511045  0.960276  0.097480  0.447538  0.097748  0.043522  0.756670   
4010  0.505994  0.961631  0.105464  0.447084  0.097761  0.043952  0.736907   
4011  0.501060  0.963514  0.113224  0.447289  0.098065  0.043852  0.718735   
4012  0.497181  0.965736  0.121204  0.447935  0.097684  0.043980  0.700745   
4013  0.492730  0.967985  0.129048  0.448210  0.097652  0.043929  0.683046   
4014  0.487984  0.970552  0.137147  0.447211  0.098017  0.044219  0.663190   
4015  0.483878  0.972058  0.144661  0.447179  0.098128  0.043876  0.645762   
4016  0.480100  0.972570  0.152082  0.448109  0.097806  0.043312  0.629897   
4017  0.476089  0.972603  0.159639  0.448173  0.097596  0.043511  0.614180   
4018  0.470672  0.972154  0.167044  0.448213  0.097463  0.043347  0.599382   
4019  0.466225  0.970958  0.174480  0.448066  0.097075  0.043585  0.585077   
4020  0.462624  0.969290  0.181816  0.448085  0.096945  0.043493  0.571497   
4021  0.458146  0.967822  0.189635  0.448089  0.096759  0.043534  0.558076   
4022  0.452870  0.966987  0.197797  0.448094  0.096641  0.043480  0.544902   
4023  0.447986  0.965518  0.205965  0.447804  0.096432  0.043497  0.530956   
4024  0.444108  0.963987  0.214884  0.447800  0.096272  0.043516  0.517288   
4025  0.439237  0.961938  0.223742  0.447584  0.096043  0.043398  0.503301   
4026  0.434039  0.960554  0.233430  0.447377  0.096088  0.043383  0.490578   
4027  0.429162  0.958419  0.243273  0.447356  0.095743  0.043270  0.477822   
4028  0.424764  0.956456  0.253615  0.447343  0.095533  0.043288  0.467107   
4029  0.420210  0.954821  0.264729  0.447331  0.095146  0.043367  0.457828   
4030  0.415205  0.953217  0.276003  0.447321  0.094924  0.043467  0.451516   
4031  0.410454  0.951309  0.288038  0.447316  0.094673  0.043637  0.447195   
4032  0.406161  0.949621  0.299935  0.447414  0.094404  0.043936  0.447570   
4033  0.401562  0.947863  0.312901  0.447525  0.094004  0.044406  0.446177   
4034  0.396791  0.946150  0.326215  0.447871  0.093697  0.045342  0.442834   
4035  0.392619  0.944012  0.338988  0.448445  0.093374  0.047004  0.440127   
4036  0.388589  0.942443  0.350914  0.447880  0.094232  0.049083  0.439229   
4037  0.384596  0.940871  0.362115  0.447604  0.094297  0.051640  0.437672   
4038  0.380390  0.942303  0.374583  0.444669  0.097126  0.053802  0.437692   
4039  0.376812  0.943929  0.385915  0.443235  0.098140  0.057847  0.437616   
4040  0.376345  0.945864  0.397520  0.442318  0.098922  0.062338  0.437441   
4041  0.373506  0.948583  0.408046  0.440233  0.100678  0.068281  0.438060   
4042  0.369117  0.952351  0.416625  0.438190  0.103580  0.074945  0.438051   
4043  0.365712  0.954526  0.425479  0.435759  0.107673  0.082810  0.438731   
4044  0.364353  0.954738  0.434494  0.433404  0.112919  0.091088  0.439025   
4045  0.362149  0.955975  0.442964  0.429883  0.119869  0.101290  0.439979   
4046  0.357867  0.957519  0.449158  0.425781  0.129184  0.112561  0.440549   
4047  0.354851  0.957959  0.457115  0.417646  0.139614  0.127915  0.441123   
4048  0.352622  0.957660  0.465403  0.409010  0.147944  0.145439  0.441125   
4049  0.349562  0.958056  0.472996  0.399853  0.153085  0.163181  0.441568   

      L_Foot_Y  L_Foot_Z  
4

Predicited Values


Waist_X   Waist_Y   Waist_Z  R_Foot_X  R_Foot_Y  R_Foot_Z  L_Foot_X  \
4000  0.976676  1.224183  0.289238 -0.496335  0.053867 -0.043498  0.865819   
4001  0.950934  1.210933  0.300699 -0.506135  0.052749 -0.019599  0.873998   
4002  0.925361  1.197943  0.312225 -0.514672  0.052463  0.002984  0.880861   
4003  0.898110  1.184754  0.323552 -0.518997  0.052893  0.025483  0.885049   
4004  0.870596  1.172180  0.333662 -0.519373  0.054445  0.046371  0.886216   
4005  0.842546  1.159517  0.344233 -0.518455  0.056463  0.066589  0.885809   
4006  0.815824  1.147585  0.354245 -0.516732  0.059069  0.085118  0.883878   
4007  0.788414  1.135978  0.363500 -0.511211  0.062655  0.103100  0.878378   
4008  0.762003  1.125182  0.371663 -0.503980  0.066878  0.119850  0.870706   
4009  0.735495  1.114798  0.379169 -0.493962  0.071835  0.136177  0.860058   
4010  0.709318  1.104973  0.385494 -0.480940  0.077525  0.152238  0.846115   
4011  0.684416  1.095954  0.390867 -0.466669  0.083552  0.167791  0.830458   
4012  0.660509  1.087606  0.395156 -0.452427  0.089923  0.183246  0.813351   
4013  0.636370  1.079752  0.398385 -0.434636  0.096838  0.199738  0.793527   
4014  0.611334  1.072404  0.399886 -0.413480  0.104681  0.217796  0.770366   
4015  0.587391  1.065872  0.399864 -0.390492  0.112881  0.237442  0.745170   
4016  0.564533  1.060154  0.397988 -0.366591  0.121524  0.259783  0.717565   
4017  0.541590  1.055078  0.394300 -0.337541  0.130895  0.284781  0.686405   
4018  0.518180  1.050709  0.387990 -0.304435  0.141313  0.312195  0.651199   
4019  0.496597  1.046943  0.380897 -0.269973  0.151629  0.340976  0.615220   
4020  0.475542  1.043524  0.372586 -0.232858  0.162407  0.371599  0.576542   
4021  0.456593  1.040430  0.364801 -0.196586  0.172615  0.401032  0.539849   
4022  0.437558  1.037541  0.356855 -0.159136  0.183140  0.430216  0.503015   
4023  0.421793  1.034603  0.351074 -0.125513  0.192252  0.456381  0.470691   
4024  0.406802  1.031611  0.346160 -0.092680  0.201132  0.481534  0.439564   
4025  0.394667  1.028484  0.343763 -0.063725  0.208549  0.503252  0.413610   
4026  0.383449  1.025322  0.342435 -0.036687  0.215500  0.523334  0.389785   
4027  0.374466  1.021966  0.343284 -0.012267  0.221239  0.541335  0.369765   
4028  0.366849  1.018457  0.345263  0.010247  0.226303  0.558417  0.351261   
4029  0.360769  1.014857  0.348987  0.031132  0.230373  0.574262  0.335845   
4030  0.355438  1.011311  0.353382  0.050697  0.233915  0.589386  0.321705   
4031  0.351460  1.007571  0.359094  0.069037  0.236550  0.604210  0.309030   
4032  0.348179  1.003819  0.365347  0.086246  0.238588  0.618763  0.296895   
4033  0.345602  0.999959  0.372440  0.102339  0.239853  0.633427  0.285417   
4034  0.343469  0.996078  0.379977  0.117491  0.240447  0.648144  0.274036   
4035  0.341403  0.992119  0.388193  0.130977  0.240229  0.662780  0.263263   
4036  0.339155  0.988076  0.396830  0.142792  0.239199  0.677421  0.252486   
4037  0.336801  0.983870  0.405891  0.152838  0.237116  0.692085  0.241604   
4038  0.333105  0.979750  0.414312  0.161487  0.234518  0.705852  0.229448   
4039  0.330032  0.975605  0.422764  0.169016  0.231014  0.719067  0.217504   
4040  0.328282  0.971520  0.431214  0.176834  0.226859  0.731885  0.206181   
4041  0.324529  0.967723  0.438819  0.184827  0.222666  0.742995  0.194192   
4042  0.319104  0.964336  0.445151  0.192473  0.218583  0.751217  0.182009   
4043  0.314059  0.961267  0.451263  0.202130  0.214608  0.757850  0.170872   
4044  0.310310  0.958472  0.457469  0.214932  0.210587  0.763316  0.161033   
4045  0.304991  0.956055  0.462331  0.227870  0.206989  0.764946  0.150830   
4046  0.298788  0.954124  0.465799  0.241492  0.203805  0.762510  0.141203   
4047  0.293078  0.952430  0.469163  0.256913  0.200933  0.758058  0.132249   
4048  0.288414  0.950995  0.472476  0.274387  0.198202  0.751966  0.124431   
4049  0.283392  0.949928  0.475184  0.291758  0.195881  0.742996  0.117925   

      L_Foot_Y  L_Foot_Z  
4

# Write Results to File 

In [179]:
results_path = "../results/"

for column in toWriteActual.columns:
    toWriteActual.rename(columns={column : "Actual_" + column}, inplace=True)

for column in toWritePred.columns:
    toWritePred.rename(columns={column : "Pred_" + column}, inplace=True)

results = pd.concat([toWriteActual, toWritePred], axis=1)
display(results)

output = results_path+ "output.csv"
results.to_csv(output, index = False)



Actual_Waist_X  Actual_Waist_Y  Actual_Waist_Z  Actual_R_Foot_X  \
0           0.060439        1.022620       -0.098646         0.296409   
1           0.060260        1.022620       -0.098646         0.296409   
2           0.059955        1.022620       -0.098769         0.296418   
3           0.059620        1.022658       -0.099001         0.296458   
4           0.059283        1.022695       -0.099210         0.296351   
...              ...             ...             ...              ...   
5395       -0.266650        1.028392       -0.104049        -0.055547   
5396       -0.263761        1.024829       -0.101151        -0.055403   
5397       -0.271885        1.032776       -0.107868        -0.054945   
5398       -0.268666        1.028839       -0.104847        -0.054282   
5399       -0.275608        1.036180       -0.110867        -0.053518   

      Actual_R_Foot_Y  Actual_R_Foot_Z  Actual_L_Foot_X  Actual_L_Foot_Y  \
0            0.111177        -0.002579        -0.105350         0.107512   
1            0.111177        -0.002579        -0.105350         0.107512   
2            0.111177        -0.002579        -0.105350         0.107433   
3            0.111177        -0.002579        -0.105350         0.107417   
4            0.111177        -0.002579        -0.105444         0.107411   
...               ...              ...              ...              ...   
5395         0.211484         0.045802        -0.325084         0.122200   
5396         0.215707         0.044948        -0.325417         0.121903   
5397         0.219580         0.044346        -0.325417         0.121905   
5398         0.222948         0.044158        -0.325470         0.121905   
5399         0.225989         0.044157        -0.325380         0.121905   

      Actual_L_Foot_Z  Pred_Waist_X  Pred_Waist_Y  Pred_Waist_Z  \
0            0.008089      0.220943      1.013334      0.143499   
1            0.008089      0.220573      1.013352      0.143619   
2            0.008048      0.220180      1.013364      0.143694   
3            0.007960      0.219799      1.013369      0.143689   
4            0.007911      0.219224      1.013377      0.143643   
...               ...           ...           ...           ...   
5395         0.065459     -0.332323      0.983205     -0.058999   
5396         0.065412     -0.333360      0.983648     -0.057928   
5397         0.065404     -0.334303      0.984181     -0.056783   
5398         0.065396     -0.334956      0.984779     -0.055500   
5399         0.065388     -0.335269      0.985408     -0.054083   

      Pred_R_Foot_X  Pred_R_Foot_Y  Pred_R_Foot_Z  Pred_L_Foot_X  \
0         -0.211455       0.113909       0.241544       0.342301   
1         -0.211553       0.114130       0.241542       0.342526   
2         -0.211643       0.114310       0.241550       0.342751   
3         -0.211898       0.114430       0.241617       0.343008   
4         -0.212029       0.114606       0.241705       0.343034   
...             ...            ...            ...            ...   
5395      -0.325814       0.159368      -0.105212      -0.483079   
5396      -0.343283       0.162712      -0.114889      -0.477255   
5397      -0.360225       0.166057      -0.124497      -0.470918   
5398      -0.376179       0.169332      -0.133578      -0.464236   
5399      -0.391227       0.172501      -0.142130      -0.457248   

      Pred_L_Foot_Y  Pred_L_Foot_Z  
0          0.102949      -0.439054  
1          0.102511      -0.438521  
2          0.102095      -0.438064  
3          0.101757      -0.437876  
4          0.101401      -0.437544  
...             ...            ...  
5395       0.121700      -0.202876  
5396       0.120932      -0.204384  
5397       0.120186      -0.205555  
5398       0.119449      -0.206404  
5399       0.118699      -0.207083  

[5400 rows x 18 columns]